version: "3.9"
services:

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devoleadb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    command: ["npm", "start"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=devoleadb
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
